# docker-compose.yml
services:
  videolens:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /mnt/i/nuScenes-panoptic-v1.0-all:/mnt/i/nuScenes-panoptic-v1.0-all
      - ./yolov9c.pt:/weights/yolov9c.pt
      - /mnt/c/Users/cathx/repos/NeuroCortex/chroma_db:/chroma_db
      - ./query_results:/query_results
      - ./configs:/app/configs
      - ./output.json:/app/output.json
    environment:
      - CONFIG_PATH=configs/docker.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]